services:
  - type: web
    name: hrms-lite-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
